import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  safeAreaCont: {
    flex: 1,
    backgroundColor: '#202124',
    alignItems: 'center',
  },
  searchBoxTopCont: {
    height: 60,
    backgroundColor: 'rgba(241,243,244,0.24)',
    marginTop: 10,
    width: '95%',
    borderRadius: 5,
  },
  searchBoxCont: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  drawerIconCont: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  searchNotesCont: {flex: 3},
  searchNotesText: {
    color: 'rgba(255,255,255,0.67)',
    fontSize: 16,
    fontWeight: 'bold',
  },
  changeListTypeCont: {flex: 1, alignItems: 'flex-end'},
  avatarImageCont: {flex: 1, alignItems: 'center', marginRight: -10},
  tabBarCont: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingVertical: 20,
    paddingHorizontal: 15,
    backgroundColor: 'rgba(241,243,244,0.24)',
    display: 'flex',
    flexDirection: 'row',
  },
  addNoteBtnTopCont: {
    width: 60,
    height: 60,
    position: 'absolute',
    right: 25,
    top: -35,
    backgroundColor: '#202124',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  addNoteBtnCont: {
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: 'rgba(241,243,244,0.24)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  googleAddImage: {width: 25, height: 25},
  bottomBarIconsMargin: {marginLeft: 25},
});
